name: server
description: A Supaabase Edge Functions example written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  common:
    path: ../common
  dartx: ^1.1.0
  edge: ^0.0.5
  edge_http_client: ^0.0.1+1
  googleapis: ^11.1.0
  googleapis_auth: ^1.4.0
  openai_client: ^0.0.7
  supabase: ^1.8.1
  supabase_functions: ^0.0.1

dev_dependencies:
  lints: ^2.0.1